### ISSUE TITLE
Where is libwebview.dylib ?

### ISSUE THREAD

**Issue by tandrasz** [webview-cs/webview-cs#3]
Hi, I downloaded the sample project, and tried to build it in VS for Mac. 

/Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Error MSB3030: Could not copy the file "/Users/tom/Downloads/webview-cs-master/thirdparty/webview/build/libwebview.dylib" because it was not found. (MSB3030) (Webview)

Update:
I tried to build it from the webview.h but without success.

I found the dylib in the NuGet package, but something is wrong. When I run the sample, I get:

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'webview' in DLL 'webview'.
   at Webview.Ffi.webview(String title, String url, Int32 width, Int32 height, Int32 resizable)
   at Webview.Webview.Simple(String title, IContent content, Size size, Boolean resizable) in /Users/tom/Downloads/webview-cs-master/src/Webview/Webview.cs:line 19
   at HelloWorld.Program.Main(String[] args) in /Users/tom/Downloads/webview-cs-master/examples/HelloWorld/Program.cs:line 13
bash: line 1: 30947 Abort trap: 6           "/usr/local/share/dotnet/dotnet" "/Users/tom/Downloads/webview-cs-master/examples/HelloWorld/bin/Debug/netcoreapp2.0/HelloWorld.dll"

**Comment by iwillspeak** [comment]
Native library loading should become a lot smother with #6. Closing this issue and tracking the problem in that issue instead.
